### PR TITLE
Add new theme jsonresume-theme-one.

### PR DESCRIPTION
**Pull request by PhillipChaffee**
image

### CODE REVIEW

**Comment by thomasdavis** [comment]
Looks great, merged in

**Comment by PhillipChaffee** [comment]
thanks!

**Comment by thomasdavis** [comment]
Having some issues with auto deployment, will let you know when its available

**Comment by thomasdavis** [comment]
Deployed -> https://registry.jsonresume.org/thomasdavis?theme=one

**Pull request merged**
